const navigationConstants = {
  home: 'Trang chủ',
  login: 'Đăng nhập',
  signup: 'Đăng kí thông tin',
  signup2: 'Đăng kí tài khoản',
  verifyEmail: 'Xác thực tài khoản',
  tabNav: 'Bottom Tab',
  drawerNav: 'Drawer',
  profile: 'Thông tin cá nhân',
  newsfeed: ' Bảng tin',
  chat: 'Nhắn tin',
  list: 'Danh sách',
  notify: 'Thông báo',
  create: 'Tạo bài đăng',
  post: 'Bài đăng',
  conversation: 'Hội thoại',
  comment: 'Bình luận',
  help: 'Hỗ trợ',
  setting: 'Cài đặt',
  field: 'Lĩnh vực',
  profileDetail: 'Chi tiết thông tin',
  follower: 'Người theo dõi',
  following: 'Đang theo dõi',
  profileEdit: 'Chỉnh sửa thông tin',
  search: 'Tìm kiếm',
  pickField: 'Chọn lĩnh vực',
  listField: 'Lĩnh vực',
  report: 'Báo cáo',
  videoCall: 'Gọi',
  ranking: 'Xếp hạng',
  forgot: 'Quên mật khẩu'
};

export default navigationConstants;
