export default {
  connectionError: 'Connection error',
  email: 'Email',
  emailHint: 'Enter your email',
  home: 'Home',
  homeMessage: 'Welcome',
  loading: 'Loading',
  login: 'Đăng nhập',
  logout: 'Đăng xuất',
  signup: 'Đăng kí',
  signupHint: 'Bạn chưa có tài khoản?',
  forgotPassword: 'Quên mật khẩu',
  username: 'Tên tài khoản',
  usernameHint: 'Nhập tên tài khoản',
  password: 'Mật khẩu',
  passwordHint: 'Nhập mật khẩu',
  firstName: 'Họ',
  lastName: 'Tên',
  male: 'Nam',
  female: 'Nữ',
  other: 'Khác',
  dob: 'Ngày sinh',
  myLocation: 'Nơi sống',
  gender: 'Giới tính',
  profile: 'Profile',
  profileMessage:
    'And this one has a nav, but with a different color than the login.',
  next: 'Tiếp theo',
};
